### ISSUE TITLE
Configurable Sidenav App

### ISSUE THREAD

**Issue by n0daft** [ElderByte-/ngx-starter#11]
#### Description

The idea is to implement a configurable base-component providing a side-content app structure.
Once included, the component provides:

* Main content section consisting of toolbar and content section (primary router-outlet)
* Left side content acting as main navigation (sidenav)
* Right side content (providing named router-outlet "side")

#### Motivation

As we use this structure in almost every app it would make sense to outsource it, so the same style and functionality can be ensured easily in many apps.

#### Design Goals

* Configurable App structure (full-width side nav app) with out-of-the-box support for sidenav, toolbar, content and side detail
* Configurable two-menu sidenav
   * configurable header
   * configurable body (primary)
   * configurable body (secondary)

#### Usage

How users should be able to use the features.

Example (to discuss)
```typescript
<ebs-sidenav-app> // provides main content space, a side navigation as well as named router-outlet 'side', 

  <ebs-sidenav-header>

  </ebs-sidenav-header>

  <ebs-sidenav-body-primary>

  	<ebs-sidenav-group [title]='Settings' [items]=>

  </ebs-sidenav-body-primary>

  <ebs-sidenav-body-secondary>
  </ebs-sidenav-body-secondary>

</ebs-sidenav-app>

```

**Comment by IsNull** [comment]
has been implemented with `<ebs-shell>`
