### ISSUE TITLE
Improve GlobalSearchComponent and Service

### ISSUE THREAD

**Issue by n0daft** [ElderByte-/ngx-starter#8]
There seems to be an issue on creation of using components. The canSort resolves to false. Might be caused by a subject not being used properly.

**Comment by n0daft** [comment]
Also to improve:

As the GlobalSearchService is global, in a component where the the service is not configured, the search component still hold configurations from previous component states (e.g. availableSorts).
We actually don't want to be the search as global as its name suggests. It is a context sensitive search feature. So either we change its scope or make sure it has a clean slate when the context of an app changes.

**Comment by IsNull** [comment]
no longer valid since now `<ebs-toolbar>` can be configured from any component to display context sensitive content in the header toolbar.
